### PR TITLE
Fix displays due to input.mozilla.com/org switch and add brownbags to events

### PR DESCRIPTION
**Pull request by mnoorenberghe**
Not sure if this is the latest code or not. If not, please point me there.

Thanks

### CODE REVIEW

**Comment by mnoorenberghe** [comment]
Any chance this will get reviewed? I know it's not a high priority but I'd rather not have broken-looking displays around the office.

**Comment by mnoorenberghe** [comment]
@fligtar ping? Any chance for a review?

**Comment by fligtar** [comment]
Hey Matt, sorry about the delay -- I haven't paid attention to sprightly in a long time, as you've noticed. In fact, a month or so ago IT wanted me to move it from the vm it's hosted on and I told them they should just shut it down instead since it's outdated, only on 1 display now, and seems to not be as interesting as folks.

If you'd like to take it over, talk to guillermo about it. Otherwise, even though I merged your changes, I can't really update the actual display anymore.

**Comment by mnoorenberghe** [comment]
Hey fligtar, thanks for the merge.  Sprightly is also still used on the 3rd floor engineering display and I think that the new calendars will add more value.  I'd be interested in maintaining it so I'll talk to Guillermo. Cheers

**Pull request merged**
